### ISSUE TITLE
[keycloak-gatekeeper] Immutable field error on chart update

### ISSUE THREAD

**Issue by sboschman** [gabibbo97/charts#20]
Deploying with Argo CD, which basically does a helm template and hands off the rendered resources to kubectl (no Tiller involved).

The chart version is part of the pod selector (https://github.com/gabibbo97/charts/blob/master/charts/keycloak-gatekeeper/templates/_helpers.tpl#L60). Trying to update/upgrade the existing deployment created with chart 1.4.2 results in a kubectl error:
```
kubectl failed exit status 1: The Deployment "keycloak-gatekeeper" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"keycloak-gatekeeper", "app.kubernetes.io/name":"keycloak-gatekeeper", "helm.sh/chart":"keycloak-gatekeeper-1.5.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

The selector is specified as immutable (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates):
> Note: In API version apps/v1, a Deployment’s label selector is immutable after it gets created.

Any objections against removing the chart name and version from the pod selector?

**Comment by gabibbo97** [comment]
Hi, can you provide an example of the manifest before and after the upgrade?
This is definitely a regression but I would like to check if I can fix the template

**Comment by gabibbo97** [comment]
https://github.com/gabibbo97/charts/blob/9fcd4a98001fbbb1b7cbf9ea0708e1f37f2f856e/charts/dex/templates/_helpers.tpl#L50

As you can see I fixed it inside the other charts

As for semver what should be the correct bump in your opinion?

**Comment by sboschman** [comment]
```
spec:
 progressDeadlineSeconds: 600
 replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: keycloak-gatekeeper
-      helm.sh/chart: keycloak-gatekeeper-1.4.2
+     helm.sh/chart: keycloak-gatekeeper-1.5.0
```

semver.... interesting, it is kind of a breaking change as the field is immutable, so you have to manually delete the deployment. Semver 2.x allows api breaks, but that is already Helm v3. On the other hand upgrading to 1.5.1 or 1.6.0 is not possible anyways, so might as well release it as 1.6.0 with a side note that the old deployment has to be deleted

**Comment by gabibbo97** [comment]
Hi, a fix for the v3 branch has been added and I tried to add manually to the v2 version in https://github.com/gabibbo97/charts/commit/f5850b716060ca383739d55cc587cf5bd301c1eb

**Comment by sboschman** [comment]
works :+1: , deployment now looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: keycloak-gatekeeper
    app.kubernetes.io/version: 8.0.1
    helm.sh/chart: keycloak-gatekeeper-1.6.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak-gatekeeper
      app.kubernetes.io/name: keycloak-gatekeeper
```
