### ISSUE TITLE
Ability to specify labels in dex - needed for ingress certificate issue

### ISSUE THREAD

**Issue by ieugen** [gabibbo97/charts#37]
Hello,

I'm using this chart and I want to provision a certificate for it with cert-manager. 
I have defined a a cluster issuer that other services are using as well.
I need to be able to specify a label for my service/ingress so that cert-manager will work.

My solver:
```
    solvers:
    - http01:
        ingress:
          class: haproxy
      selector:
        matchLabels:
          "use-http01-solver": "true"
```

Current dex chart setup regarding labels. 
They are hardcoded in `_helpers.tpl`
```
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
```
